---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by vela.
--- DateTime: 2024/12/17 15:32
---

local hello  = wasm.load("hello.wasm")
local number = hello.add(1,1)
print(number)

local a = vela.struct[[
	string   name,
	int      age,
	[]struct   {
		int    a,
		int    b
	}
]]

a.call = function(v)
	print(v)
end


print(a.name)
print(a.age)

